services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=course'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=course'
    ports:
      - '50000:3306'
